language: "perl"
os:
    #- linux
    - osx
perl:
    - "5.10"
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    packages:
    # install toolchains
    - clang-3.9

install: "echo"
before_script:
    - uname -a
    - echo $TRAVIS_OS_NAME
    - gcc --version
    - clang --version
#    - ls /Applications/Xcode.app/Contents/Developer/usr/bin/
#    - ls /Library/Developer/CommandLineTools/usr/bin/
    - if [ "$TRAVIS_OS_NAME" != "linux" ] ; then cat /etc/paths ; export PATH="$PATH:/Library/Developer/CommandLineTools/usr/bin/:/Applications/Xcode.app/Contents/Developer/usr/bin/"; fi
    - echo $PATH
    - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then sudo apt-get update -qq || sudo apt-get update -qq ; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then sudo apt-get install -y libffi-dev || sudo apt-get install -y libffi-dev ; fi
    - git fetch --unshallow
    - git clone --depth 1 git://github.com/perl6/nqp

script:
    - "perl Configure.pl --prefix=/tmp/moar $MVM_OPTIONS --debug --optimize --cc=\"$CC\";"
    #- perl Configure.pl --compiler=clang --coverage --optimize=0 --debug=3 --prefix=/tmp/moar;
    - make install
    - cd nqp; perl Configure.pl --prefix=/tmp/moar --backends=moar
    - "make"
    - "make test"
    - "if [ $COVERAGE == 1 ] ; then llvm-profdata merge -o MoarVM.gcov coverage.profraw; rm coverage.profraw; fi"

branches:
   only:
     - /.*/
    # - /smoke-me/

#notifications:
 # irc:
#    channels:
#    - "irc.freenode.net#moarvm"
#    on_success: change
#    on_failure: always
#    template:
#      - "MoarVM build %{result}. %{author} '%{commit_message}'"
#      - "%{build_url} %{compare_url}"

env:
  matrix:
#    - MVM_OPTIONS="--no-jit"  CC="gcc"
#    - MVM_OPTIONS=""          CC="gcc"
#    - MVM_OPTIONS="--no-jit"  CC="clang"
#    - MVM_OPTIONS=""          CC="clang"
#    - MVM_OPTIONS="--has-libffi --no-jit"  CC="gcc"
#    - MVM_OPTIONS="--has-libffi"           CC="gcc"
#    - MVM_OPTIONS="--has-libffi --no-jit"  CC="clang"
#    - MVM_OPTIONS="--has-libffi"           CC="clang"
# Coverage build
    - MVM_OPTIONS="--coverage --optimize=0 --debug=3" CC="clang" COVERAGE=1 LLVM_PROFILE_FILE="coverage.profraw"

after_success:
  - pwd
  - find .
  - "if [ $COVERAGE == 1 ] ; then bash <(curl -s https://codecov.io/bash) -f MoarVM.gcov ; fi"
  - ls -l

matrix:
  exclude:
  - os: osx
    env: MVM_OPTIONS="--has-libffi --no-jit"  CC="gcc"
  - os: osx
    env: MVM_OPTIONS="--has-libffi"           CC="gcc"
  - os: osx
    env: MVM_OPTIONS="--no-jit"               CC="gcc"
  - os: osx
    env: MVM_OPTIONS=""                       CC="gcc"
  - os: osx
    env: MVM_OPTIONS="--has-libffi --no-jit"  CC="clang"
  - os: osx
    env: MVM_OPTIONS="--has-libffi"           CC="clang"
