language: "perl"
os:
    - linux
    - osx
perl:
    - "5.10"
install: "echo"
before_script:
    - uname -a
    - gcc --version
    - clang --version
    - MVM_debug="--debug"; MVM_optimize="--optimize"
    - if [ "$COVERAGE" ]; then MVM_debug="--debug=3"; MVM_optimize="--optimize=0"; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then sudo apt-get update -qq || sudo apt-get update -qq ; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then sudo apt-get install -y libffi-dev || sudo apt-get install -y libffi-dev ; fi
    - git fetch --unshallow
    - git clone --depth 1 git://github.com/perl6/nqp

script:
    - export MOAR_PREFIX="/tmp/moar"; export MOAR_FOLDER="$TRAVIS_BUILD_DIR"
    - export NQP_FOLDER="$(readlink -f ./nqp)"
    - "perl Configure.pl --prefix=$MOAR_PREFIX $MVM_OPTIONS $MVM_debug $MVM_optimize --cc=\"$CC\"; make install; cd nqp; perl Configure.pl --prefix=$MOAR_PREFIX --backends=moar; make; make test"
    - if [ "$COVERAGE" ]; then git clone --depth 1 'https://github.com/samcv/MoarVM-cover.git' && cp -v MoarVM-cover/html-cover.sh . && cp -v MoarVM-cover/nqp-profile ./nqp; fi

branches:
   only:
     - master
     - coverage
     - /smoke-me/

notifications:
  irc:
    channels:
    - "irc.freenode.net#moarvm"
  #  on_success: change
  #  on_failure: always
    template:
      - "MoarVM build %{result}. %{author} '%{commit_message}'"
      - "%{build_url} %{compare_url}"

env:
  matrix:
#    - MVM_OPTIONS="--no-jit"  CC="gcc"
#    - MVM_OPTIONS=""          CC="gcc"
#    - MVM_OPTIONS="--no-jit"  CC="clang"
#    - MVM_OPTIONS=""          CC="clang"
#    - MVM_OPTIONS="--has-libffi --no-jit"  CC="gcc"
#    - MVM_OPTIONS="--has-libffi"           CC="gcc"
#    - MVM_OPTIONS="--has-libffi --no-jit"  CC="clang"
#    - MVM_OPTIONS="--has-libffi"           CC="clang"
    - MVM_OPTIONS="--coverage --optimize=0 --debug=3" CC="clang" COVERAGE=1

matrix:
  exclude:
  - os: osx
    env: MVM_OPTIONS="--has-libffi --no-jit"  CC="gcc"
  - os: osx
    env: MVM_OPTIONS="--has-libffi"           CC="gcc"
  - os: osx
    env: MVM_OPTIONS="--no-jit"               CC="gcc"
  - os: osx
    env: MVM_OPTIONS=""                       CC="gcc"
  - os: osx
    env: MVM_OPTIONS="--has-libffi --no-jit"  CC="clang"
  - os: osx
    env: MVM_OPTIONS="--has-libffi"           CC="clang"
