language: "perl"
os:
    - linux
    - osx
perl:
    - "5.10"
install: "echo"
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'deb http://apt.llvm.org/precise/ llvm-toolchain-precise main'
    packages:
      - clang-5.0
      - llvm-5.0

before_script:
    - uname -a
    - gcc --version
    - clang --version
    # Find the latest clang that is on the system
    - CLANG_LATEST=$(ls /usr/bin | grep -Ee '^clang(\-[0-9.]+)?$' | sort -r | head -n 1)
    - if [ ! "$CLANG_LATEST" = 'clang' ]; then eval "$CLANG_LATEST --version"; fi
    - if [ "$USE_CLANG_LATEST" ]; then echo "Using $CLANG_LATEST due to build setting"; CC="$CLANG_LATEST"; fi
    - MVM_debug="--debug"; MVM_optimize="--optimize"
    - if [ "$COVERAGE" ]; then MVM_debug="--debug=3"; MVM_optimize="--optimize=0"; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then sudo apt-get update -qq || sudo apt-get update -qq ; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then sudo apt-get install -y libffi-dev || sudo apt-get install -y libffi-dev ; fi
    - git fetch --unshallow
    - git clone --depth 1 git://github.com/perl6/nqp

script:
    - export MOAR_PREFIX="/tmp/moar"; export MOAR_FOLDER="$TRAVIS_BUILD_DIR"
    - export NQP_FOLDER="$(readlink -f ./nqp)"
    - perl Configure.pl --prefix=$MOAR_PREFIX $MVM_OPTIONS --cc="$CC" $MVM_debug $MVM_optimize;
    - make install;
    - cd nqp;
    - perl Configure.pl --prefix=$MOAR_PREFIX --backends=moar;
    - make;
    - make test;
    - cd ..
    - if [ "$COVERAGE" ]; then git clone --depth 1 'https://github.com/samcv/MoarVM-cover.git' && cp -v MoarVM-cover/html-cover.sh . && cp -v MoarVM-cover/nqp-profile ./nqp/ && cp -v MoarVM-cover/merge-profraw.sh ./nqp/ && ./html-cover.sh 2; fi

branches:
   only:
     - master
     - coverage
     - /smoke-me/

notifications:
  irc:
    channels:
    - "irc.freenode.net#moarvm"
  #  on_success: change
  #  on_failure: always
    template:
      - "MoarVM build %{result}. %{author} '%{commit_message}'"
      - "%{build_url} %{compare_url}"

env:
  matrix:
#    - MVM_OPTIONS="--no-jit               CC='gcc'"
#    - MVM_OPTIONS="                       CC='gcc'"
#    - MVM_OPTIONS="--no-jit               CC='clang'"
#    - MVM_OPTIONS="                       CC='clang'"
#    - MVM_OPTIONS="--has-libffi --no-jit  CC='gcc'"
#    - MVM_OPTIONS="--has-libffi           CC='gcc'"
#    - MVM_OPTIONS="--has-libffi --no-jit  CC='clang'"
#    - MVM_OPTIONS="--has-libffi           CC='clang'"
    - MVM_OPTIONS="--compiler=clang --coverage --optimize=0 --debug=3" COVERAGE=1 USE_CLANG_LATEST=1 CC='clang'

matrix:
  exclude:
  - os: osx
    env: MVM_OPTIONS="--has-libffi --no-jit"  CC="gcc"
  - os: osx
    env: MVM_OPTIONS="--has-libffi"           CC="gcc"
  - os: osx
    env: MVM_OPTIONS="--no-jit"               CC="gcc"
  - os: osx
    env: MVM_OPTIONS=""                       CC="gcc"
  - os: osx
    env: MVM_OPTIONS="--has-libffi --no-jit"  CC="clang"
  - os: osx
    env: MVM_OPTIONS="--has-libffi"           CC="clang"
