language: "perl"
os:
    - linux
    - osx
perl:
    - "5.10"
install: "echo"
before_script:
    - uname -a
    - gcc --version
    - clang --version
    - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then sudo apt-get update -qq || sudo apt-get update -qq ; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then sudo apt-get install -y libffi-dev || sudo apt-get install -y libffi-dev ; fi
    - git fetch --unshallow
    - git clone --depth 1 git://github.com/perl6/nqp

script:
    - "perl Configure.pl --prefix=/tmp/moar $MVM_OPTIONS --debug --optimize --cc=\"$CC\"; make install; cd nqp; perl Configure.pl --prefix=/tmp/moar --backends=moar; make; make test"
    - if [ $COVERAGE == 1 ] ; then llvm-profdata merge -o MoarVM.gcov coverage.profraw ; fi

branches:
   only:
     - master
     - /smoke-me/

notifications:
  irc:
    channels:
    - "irc.freenode.net#moarvm"
    on_success: change
    on_failure: always
    template:
      - "MoarVM build %{result}. %{author} '%{commit_message}'"
      - "%{build_url} %{compare_url}"

env:
  matrix:
#    - MVM_OPTIONS="--no-jit"  CC="gcc"
#    - MVM_OPTIONS=""          CC="gcc"
#    - MVM_OPTIONS="--no-jit"  CC="clang"
#    - MVM_OPTIONS=""          CC="clang"
#    - MVM_OPTIONS="--has-libffi --no-jit"  CC="gcc"
#    - MVM_OPTIONS="--has-libffi"           CC="gcc"
#    - MVM_OPTIONS="--has-libffi --no-jit"  CC="clang"
#    - MVM_OPTIONS="--has-libffi"           CC="clang"
# Coverage build
    - MVM_OPTIONS="--compiler=clang --coverage --optimize=0 --debug=3" COVERAGE=1 LLVM_PROFILE_FILE="coverage.profraw"

after_success:
  - if [ $COVERAGE == 1 ] ; then bash <(curl -s https://codecov.io/bash) ; fi

matrix:
  exclude:
  - os: osx
    env: MVM_OPTIONS="--has-libffi --no-jit"  CC="gcc"
  - os: osx
    env: MVM_OPTIONS="--has-libffi"           CC="gcc"
  - os: osx
    env: MVM_OPTIONS="--no-jit"               CC="gcc"
  - os: osx
    env: MVM_OPTIONS=""                       CC="gcc"
  - os: osx
    env: MVM_OPTIONS="--has-libffi --no-jit"  CC="clang"
  - os: osx
    env: MVM_OPTIONS="--has-libffi"           CC="clang"
